# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Osterman
email: john@ostermancommunications.com
description: > # this means to ignore newlines until "baseurl:"
  Freelance digital publications, data visualization, front-end development, and communications services.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: JohnAOsterman
github_username:  ostermanj
linkedin_username: john-osterman-32714012
# Build settings
markdown: kramdown
